-- PROBLEM: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
SELECT * FROM Bonusuri
WAITFOR DELAY '00:00:10'
SELECT * FROM Bonusuri
COMMIT TRAN
